AWSTemplateFormatVersion: 2010-09-09
Description: |
  This Template for Kittens Carousel Static Website on EC2.
Resources:
  MySecurity:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: Enable HTTP for Apache Server  #required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 
      Tags:
        - Key: Name
          Value: My first security group
  MyServer:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-0947d2ba12ee1ff75
      InstanceType: t2.micro
      KeyName: cherry
      SecurityGroupIds:
        - !Ref MySecurity
      Tags:
        - Key: Name 
          Value: !Sub Web Server of ${AWS::StackName} Stack 
      UserData:
        Fn::Base64:
          !Sub | 
            #! /bin/bash
            yum update -y
            yum install httpd -y 
            cd /var/www/html/ 
            wget https://raw.githubusercontent.com/ftmkrz/my-projects/master/kitten-project/static-web/index.html
            wget https://raw.githubusercontent.com/ftmkrz/my-projects/master/kitten-project/static-web/cat0.jpg
            wget https://raw.githubusercontent.com/ftmkrz/my-projects/master/kitten-project/static-web/cat1.jpg 
            wget https://raw.githubusercontent.com/ftmkrz/my-projects/master/kitten-project/static-web/cat2.jpg 
            systemctl start http 
            systemctl enable http 
Outputs:
  WebsiteURL:
    Description: Kittens Carousel Application  URL 
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt MyServer.PublicDnsName 
  