version: '3'
services: 
    app: 
        build: .
        ports:
            - "80:80"
        volumes:
            - .:/app
        networks:
            - clarusnet
networks:
    clarusnet:
        driver: bridge

    
           
    
