---
- hosts: localhost
  vars_files:
  - credentials.yml
  tasks:
   - name: stop instances
     ec2:
     aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
     aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
     ec2_region: "{{ AWS_REGION }}"
     state: stopped
     


